projeto_prod:
  target: dev
  outputs:
    dev:
      dataset: "{{env_var('GCP_DEV_SCHEMA')}}"
      job_execution_timeout_seconds: 3600
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: "{{env_var('GCP_DEV_PROJECT')}}"
      threads: 4
      type: bigquery
    prod:
      dataset: "{{env_var('GCP_PROD_SCHEMA')}}"
      job_execution_timeout_seconds: 3600
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: "{{env_var('GCP_PROD_PROJECT')}}"
      threads: 4
      type: bigquery